package com.tradeforge.auth.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * WHY a record?
 * OtpVerifyRequest is pure request data — immutable, no business logic.
 * Records give us: compact syntax, auto-generated constructor, equals/hashCode/toString.
 * No builder needed: caller sets all fields at construction time.
 *
 * WHY @NotBlank on tempToken?
 * If tempToken is missing, the 2FA verify endpoint can't look up the pending session.
 * Validation catches this at the controller boundary with a 400 Bad Request —
 * before we hit the service layer.
 *
 * WHY @Size(min=6, max=6) on otp?
 * OTPs are always exactly 6 digits. A 5-char or 7-char submission is always wrong.
 * Fail early at the HTTP boundary rather than Redis lookup + compare.
 *
 * WHY trustDevice boolean (not Boolean)?
 * Primitive boolean defaults to false — safe default.
 * If Angular omits this field from the JSON body, Jackson treats it as false (don't trust).
 */
public record OtpVerifyRequest(

        /**
         * Short-lived JWT issued during the 2FA challenge (twoFactorPending:true).
         * Identifies the pending login session in Redis.
         * WHY @NotBlank? Without it we can't do anything — fail fast.
         */
        @NotBlank(message = "Temp token is required")
        String tempToken,

        /**
         * The 6-digit OTP entered by the user.
         * Generated by SecureRandom, stored in Redis with 10-minute TTL.
         * WHY min=6 max=6? Enforces exact length — no padding attacks.
         */
        @NotBlank(message = "OTP is required")
        @Size(min = 6, max = 6, message = "OTP must be exactly 6 digits")
        String otp,

        /**
         * If true, create a TrustedDevice record and set the tf_dt HttpOnly cookie.
         * This device will skip 2FA for the next 30 days.
         * WHY false default? Safer default — explicit opt-in to trust.
         */
        boolean trustDevice
) {}
