package com.tradeforge.auth.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * WHY @Entity for WebAuthn credentials?
 * Each registered authenticator (laptop TouchID, phone FaceID, YubiKey) is stored
 * as a separate row. One user can have multiple credentials.
 * Stored persistently in DB — not Redis — because credentials last months/years.
 *
 * WebAuthn Glossary:
 * - credentialId: unique ID for the authenticator registered on this device.
 *   Generated by the authenticator during registration. Used to look up which
 *   key to verify against during authentication.
 * - publicKeyCose: the ECDSA or RSA public key in CBOR Object Signing and Encryption
 *   (COSE) format. Server verifies the authentication signature against this key.
 * - signCount: monotonically increasing counter. Authenticator increments on each use.
 *   If stored count > submitted count, it may indicate a cloned authenticator.
 * - aaguid: Authenticator Attestation GUID — identifies the authenticator model.
 *   Optional; set to null for privacy-preserving authenticators.
 *
 * WHY no Lombok? Consistent with the rest of the project (Java 21, no Lombok).
 */
@Entity
@Table(name = "webauthn_credentials", schema = "auth")
public class WebAuthnCredential {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    // WHY UUID PK? Allows safe deletion by ID without exposing sequential enumeration.
    private UUID id;

    // WHY @ManyToOne LAZY? A user can have multiple credentials.
    // LAZY load avoids fetching the full User entity every time we load a credential.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // WHY unique? Two authenticators cannot share the same credential ID.
    // The credential ID uniquely identifies one authenticator across the entire platform.
    @Column(name = "credential_id", nullable = false, unique = true)
    private String credentialId;

    // WHY @Lob / columnDefinition TEXT?
    // Public key in COSE format can be large (up to a few hundred bytes in base64).
    // TEXT avoids VARCHAR(255) truncation.
    @Column(name = "public_key_cose", nullable = false, columnDefinition = "TEXT")
    private String publicKeyCose;

    // WHY track signCount? Clone detection — if count goes backwards, credential was cloned.
    @Column(name = "sign_count", nullable = false)
    private long signCount = 0L;

    // WHY nullable aaguid? Privacy-preserving authenticators don't send aaguid.
    @Column(name = "aaguid")
    private String aaguid;

    // WHY deviceName? User-facing label in the settings page.
    // "MacBook TouchID", "iPhone FaceID", "YubiKey 5C" — human-readable.
    @Column(name = "device_name")
    private String deviceName;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    // WHY lastUsedAt nullable? Newly registered credential hasn't been used for auth yet.
    @Column(name = "last_used_at")
    private LocalDateTime lastUsedAt;

    // WHY no-arg constructor? JPA requires it to hydrate entities from ResultSet rows.
    public WebAuthnCredential() {}

    private WebAuthnCredential(UUID id, User user, String credentialId, String publicKeyCose,
                                long signCount, String aaguid, String deviceName,
                                LocalDateTime createdAt, LocalDateTime lastUsedAt) {
        this.id = id;
        this.user = user;
        this.credentialId = credentialId;
        this.publicKeyCose = publicKeyCose;
        this.signCount = signCount;
        this.aaguid = aaguid;
        this.deviceName = deviceName;
        this.createdAt = createdAt;
        this.lastUsedAt = lastUsedAt;
    }

    // WHY @PrePersist? Auto-set createdAt before INSERT — callers don't need to remember.
    @PrePersist
    void onCreate() {
        createdAt = LocalDateTime.now();
    }

    // ── Getters & Setters ──────────────────────────────────────────────────
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public String getCredentialId() { return credentialId; }
    public void setCredentialId(String credentialId) { this.credentialId = credentialId; }

    public String getPublicKeyCose() { return publicKeyCose; }
    public void setPublicKeyCose(String publicKeyCose) { this.publicKeyCose = publicKeyCose; }

    public long getSignCount() { return signCount; }
    public void setSignCount(long signCount) { this.signCount = signCount; }

    public String getAaguid() { return aaguid; }
    public void setAaguid(String aaguid) { this.aaguid = aaguid; }

    public String getDeviceName() { return deviceName; }
    public void setDeviceName(String deviceName) { this.deviceName = deviceName; }

    public LocalDateTime getCreatedAt() { return createdAt; }

    public LocalDateTime getLastUsedAt() { return lastUsedAt; }
    public void setLastUsedAt(LocalDateTime lastUsedAt) { this.lastUsedAt = lastUsedAt; }

    // ── Builder ────────────────────────────────────────────────────────────
    public static Builder builder() { return new Builder(); }

    public static class Builder {
        private UUID id;
        private User user;
        private String credentialId;
        private String publicKeyCose;
        private long signCount = 0L;
        private String aaguid;
        private String deviceName;
        private LocalDateTime createdAt;
        private LocalDateTime lastUsedAt;

        public Builder id(UUID id) { this.id = id; return this; }
        public Builder user(User user) { this.user = user; return this; }
        public Builder credentialId(String c) { this.credentialId = c; return this; }
        public Builder publicKeyCose(String p) { this.publicKeyCose = p; return this; }
        public Builder signCount(long s) { this.signCount = s; return this; }
        public Builder aaguid(String a) { this.aaguid = a; return this; }
        public Builder deviceName(String d) { this.deviceName = d; return this; }
        public Builder createdAt(LocalDateTime t) { this.createdAt = t; return this; }
        public Builder lastUsedAt(LocalDateTime t) { this.lastUsedAt = t; return this; }

        public WebAuthnCredential build() {
            return new WebAuthnCredential(id, user, credentialId, publicKeyCose,
                    signCount, aaguid, deviceName, createdAt, lastUsedAt);
        }
    }
}
