// WHY selectors for orders?
// Selectors are memoized — computed values are cached until state changes.
// Components subscribe to selectors, not raw state slices.
// Derived/computed data (e.g., orders grouped by status) is computed here once,
// not in every component's template.

import { createSelector } from '@ngrx/store';
import { selectOrdersState } from './order.reducer';
import { OrderStatus } from '../../../core/models/order.models';

/**
 * WHY re-export from feature?
 * selectOrdersState, selectOrders etc. are auto-generated by createFeature.
 * We re-export them plus add derived selectors here as a single import point.
 * Components import from order.selectors.ts — one file, not multiple.
 */
export { selectOrders, selectLoading, selectPlacing, selectError, selectSelectedSymbol }
  from './order.reducer';

/**
 * WHY selectPendingOrders?
 * Orders page shows pending orders in a separate section (actionable — can cancel).
 * Computed selector: derived from selectOrders, re-evaluated only when orders change.
 * Components don't filter in the template — selectors do the work.
 */
export const selectPendingOrders = createSelector(
  selectOrdersState,
  state => state.orders.filter(o => o.status === 'PENDING')
);

export const selectCompletedOrders = createSelector(
  selectOrdersState,
  state => state.orders.filter(o => o.status === 'COMPLETE')
);

export const selectOrderCount = createSelector(
  selectOrdersState,
  state => state.orders.length
);

export const selectOrdersByStatus = (status: OrderStatus) => createSelector(
  selectOrdersState,
  state => state.orders.filter(o => o.status === status)
);

// WHY selectRecentOrders? place-order sidebar shows last 5 orders at a glance.
// Sorted newest-first by placedAt so the most recent activity is always visible.
export const selectRecentOrders = createSelector(
  selectOrdersState,
  state => [...state.orders]
    .sort((a, b) => new Date(b.placedAt).getTime() - new Date(a.placedAt).getTime())
    .slice(0, 5)
);
